# ========================
# Server
# ========================
server.port=9091
 
# ========================
# PostgreSQL
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/tritux_rh
spring.datasource.username=tritux_admin
spring.datasource.password=Tritux@2025!
spring.datasource.driver-class-name=org.postgresql.Driver
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
 
# ========================
# File Upload
# ========================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
 
# ========================
# Services externes
# ========================
python.service.url=http://localhost:8001
 
# ========================
# n8n Webhooks
# ========================
n8n.webhook.url=http://localhost:5678/webhook/extract-cv
n8n.webhook.scoring.url=http://localhost:5678/webhook/scoring-cv
n8n.chat.webhook.url=http://localhost:5678/webhook/tritux-chat
n8n.chat-audio.webhook.url=http://localhost:5678/webhook/tritux-chat-audio
 
# ========================
# Uploads
# ========================
uploads.externes.dir=uploads/externes/
 
# ========================
# CORS
# ========================
cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://localhost:4173
 
# ========================
# Keycloak / Spring Security
# ========================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/tritux
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/tritux/protocol/openid-connect/certs
# ========================
# Google Calendar OAuth2
# ========================

google.oauth.client-id=160356292512-encicujj8rbmmus1djcmoje5mt4qgfa9.apps.googleusercontent.com
google.oauth.client-secret=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
google.oauth.redirect-uri=http://localhost:3000/google-callback